# Site settings
title: Annalytics
company: Annalytics Ltd
email: brett@annalytics.co.uk
description: "Pragmatic coding"
baseurl: ""
url: "http://annalytics.co.uk"
username: brettwold

# Build settings
markdown: kramdown
permalink: pretty
highligher: pygments
